

CREATE DATABASE ProductsDB;
USE ProductsDB;


CREATE TABLE ProductsTAB(
  Id INT NOT NULL AUTO_INCREMENT,
  Name VARCHAR(255) NOT NULL,
  Price FLOAT NOT NULL, 
  UpdateDate DATETIME NOT NULL DEFAULT NOW(),
  PRIMARY KEY(Id)
);


INSERT INTO ProductsTAB(Name, Price)
VALUES ("apple", 3.01);

